language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install python-numpy python-scipy
install: pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
script:  python setup.py test